dist: trusty
sudo: required
language: node_js
node_js:
  - "4.5"
  - "5"
  - "6"
os:
  - linux
  - osx

env:
  matrix:
    - SCRIPT=lint
    - SCRIPT=test:cover

matrix:
  fast_finish: true

install:
  - npm install --no-optional

script:
  - npm run-script $SCRIPT

after_script:
  - npm install coveralls
  - cat coverage/lcov.info | node_modules/.bin/coveralls