dist: trusty
sudo: required
language: node_js
node_js:
  - "4.5"
  - "5"
  - "6"
os:
  - linux
  - osx

env:
  matrix:
    - SCRIPT=lint
    - SCRIPT=test

matrix:
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
  - npm install --no-optional

script:
  - npm run-script $SCRIPT
